FILE(READ "${CHUCHO_UNIT_TEST_LOCATION}" CHUCHO_UNIT_TEST_DIR)
SET(ENV{${CHUCHO_LD_ENV_VAR}} "${CHUCHO_LD_ENV_VALUE}")
EXECUTE_PROCESS(COMMAND "${CHUCHO_UNIT_TEST_DIR}/unit-test" $ENV{CHUCHO_GTEST_OPTS})
