FILE(MAKE_DIRECTORY exploded)
EXECUTE_PROCESS(COMMAND "${CHUCHO_AR}" -x "${CHUCHO_ARCHIVE_TO_ADD}"
                WORKING_DIRECTORY exploded)
FILE(GLOB CHUCHO_ARCHIVE_OBJECTS exploded/*${CHUCHO_OBJECT_EXTENSION})
EXECUTE_PROCESS(COMMAND "${CHUCHO_AR}" -r "${CHUCHO_ARCHIVE_TO_UPDATE}" ${CHUCHO_ARCHIVE_OBJECTS})
FILE(REMOVE_RECURSE exploded)
